# Generated by Django 5.1.5 on 2025-01-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('modality', models.CharField(max_length=100)),
                ('ubigeo', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('reposted', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('time_response', models.CharField(blank=True, max_length=100, null=True)),
                ('application_type', models.CharField(blank=True, max_length=100, null=True)),
                ('listed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
