# Generated by Django 5.1.5 on 2025-01-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='post_id',
            field=models.CharField(max_length=255),
        ),
    ]
