# Generated by Django 5.1.5 on 2025-01-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobposting_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
